#!/usr/bin/env python3
"""
gen-poc.py - generate a minimal Java serialize->deserialize PoC SKELETON from a
find-gadget-deser SARIF result.

Given the SARIF produced by `find-gadget-deser.py --sarif out.sarif` and a result
index, this emits a Java harness skeleton that:
  - builds the gadget object graph (TODO marker for the researcher),
  - serializes it to a byte[],
  - deserializes it via ObjectInputStream (the sink the tool reported),
  - prints what action is expected to fire.

It is a SKELETON: it does not construct the real gadget chain (that is the
researcher's validation step). It removes boilerplate so you can focus on arming
the payload.

Usage:
  python3 tools/gen-poc.py --sarif reachable.sarif              # list results
  python3 tools/gen-poc.py --sarif reachable.sarif --index 0 -o PoC.java
"""
import argparse
import json
import os
import re
import sys

CHAIN_RE = re.compile(r"([A-Za-z_][\w.$]*)\.([A-Za-z_]\w*)\(\)\s*->\s*(.+?)\s*@\s*([\w./\\]+):(\d+)")


def parse_result(res):
    """Extract the FIRST chain from a find-gadget-deser result message."""
    msg = (res.get("message", {}).get("text", "") or "")
    m = CHAIN_RE.search(msg)
    if not m:
        return None
    return {
        "class": m.group(1), "method": m.group(2),
        "kind": m.group(3).strip(), "file": m.group(4), "line": m.group(5),
    }


def skeleton(info):
    cls = info["class"]
    kind = info["kind"]
    is_deser = "deserialization" in kind.lower()
    action = kind.replace("RCE:", "").strip() if kind.startswith("RCE:") else kind
    sink_note = ("the reported deserialization sink (ObjectInputStream.readObject)" if is_deser
                 else f"code that reaches the {action} RCE action")
    k = json.dumps(kind)
    cm = json.dumps(cls + "." + info["method"])
    return f'''/*
 * PoC skeleton - generated by tools/gen-poc.py
 * Chain reported by find-gadget-deser:
 *   start: {cls}.{info["method"]}()  ->  {kind}  @  {info["file"]}:{info["line"]}
 *
 * GOAL: trigger {sink_note} by deserializing an attacker-controlled object graph.
 *
 * STEP 1 (TODO): construct the gadget object graph that, when deserialized,
 *   causes {cls}.{info["method"]}() to run and reach the dangerous {kind}.
 * STEP 2: serialize it below.
 * STEP 3: feed the bytes to the application's real sink (or the harness below)
 *   and confirm the {kind} action fires.
 *
 * WARNING: only test against systems you own / are authorized to assess.
 */
import java.io.*;

public class PoC {{
    public static void main(String[] args) throws Exception {{
        Object gadget = buildGadget();
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (ObjectOutputStream oos = new ObjectOutputStream(bos)) {{
            oos.writeObject(gadget);
        }}
        byte[] payload = bos.toByteArray();
        System.out.println("[*] serialized payload: " + payload.length + " bytes");
        System.out.println("[*] deserializing to trigger {k} ...");
        try (ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(payload))) {{
            Object result = ois.readObject();
            System.out.println("[*] deserialized: " + result);
        }}
        System.out.println("[!] If the {action} action fired above, the chain is exploitable.");
    }}

    private static Object buildGadget() {{
        // TODO: construct the gadget object graph for {cls}.{info["method"]}() -> {kind}.
        throw new UnsupportedOperationException("arm the payload: build the gadget graph for " + {cm});
    }}
}}
'''


def main():
    ap = argparse.ArgumentParser(description="Generate a Java PoC skeleton from a find-gadget-deser SARIF result.")
    ap.add_argument("--sarif", required=True, help="SARIF from find-gadget-deser.py --sarif")
    ap.add_argument("--index", type=int, default=None, help="result index (0-based). If omitted, list and exit.")
    ap.add_argument("-o", "--out", default="PoC.java", help="output .java path")
    args = ap.parse_args()

    d = json.load(open(args.sarif, "r", encoding="utf-8"))
    results = (d.get("runs") or [{}])[0].get("results", [])
    parsed = [parse_result(r) for r in results]
    parsed = [p for p in parsed if p]
    if not parsed:
        print("no find-gadget-deser chain results parsed from SARIF", file=sys.stderr)
        print(f"(sarif had {len(results)} results; first message: " +
              ((results[0].get('message', {}).get('text', '')[:120]) if results else 'none') + ")",
              file=sys.stderr)
        sys.exit(1)
    if args.index is None:
        for i, p in enumerate(parsed):
            print(f"[{i}] {p['class']}.{p['method']}() -> {p['kind']} @ {p['file']}:{p['line']}")
        print("\nre-run with --index N to generate PoC.java for result N", file=sys.stderr)
        sys.exit(0)
    info = parsed[args.index]
    code = skeleton(info)
    open(args.out, "w", encoding="utf-8").write(code)
    print(f"[gen-poc] wrote {args.out} for: {info['class']}.{info['method']}() -> {info['kind']}", file=sys.stderr)
    print(code)


if __name__ == "__main__":
    main()